# Generated by Django 2.2.6 on 2019-10-05 14:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('note', models.TextField()),
                ('created_time', models.DateTimeField(default=datetime.datetime(2019, 10, 5, 14, 24, 25, 467769, tzinfo=utc))),
                ('begin_time', models.DateField()),
                ('end_time', models.DateField()),
            ],
        ),
    ]
