# Generated by Django 2.2.6 on 2019-10-05 15:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 15, 28, 43, 702110, tzinfo=utc)),
        ),
    ]
