# Generated by Django 2.2.6 on 2019-10-06 07:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_auto_20191005_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 6, 7, 37, 21, 976202, tzinfo=utc)),
        ),
    ]
