# Generated by Django 2.2.6 on 2019-10-06 15:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_auto_20191006_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 6, 15, 49, 9, 427496, tzinfo=utc)),
        ),
    ]
